#define MAX_BATCH 10

/* ----- CONV LAYER -----*/

#define CONV_MAX_KERNEL_SIZE 3
#define CONV_MAX_INPUT_DIMS 512
#define CONV_MAX_OUTPUT_DIMS 512
#define CONV_MAX_INPUT_WIDTH 226
#define CONV_MAX_INPUT_HEIGHT 226
#define CONV_MAX_OUTPUT_WIDTH 224
#define CONV_MAX_OUTPUT_HEIGHT 224
#define CONV_MAX_CONV_INPUT CONV_MAX_INPUT_DIMS*CONV_MAX_INPUT_WIDTH*CONV_MAX_INPUT_HEIGHT 
#define CONV_MAX_CONV_OUTPUT CONV_MAX_OUTPUT_DIMS*CONV_MAX_OUTPUT_WIDTH*CONV_MAX_OUTPUT_HEIGHT 
#define CONV_MAX_WEIGHT_SIZE CONV_MAX_OUTPUT_DIMS*CONV_MAX_INPUT_DIMS*CONV_MAX_KERNEL_SIZE*CONV_MAX_KERNEL_SIZE

/* ----- MAX POOL LAYER -----*/

#define MPOOL_MAX_INPUT_DIMS 512
#define MPOOL_MAX_OUTPUT_DIMS 512
#define MPOOL_MAX_INPUT_WIDTH 226
#define MPOOL_MAX_INPUT_HEIGHT 226
#define MPOOL_MAX_OUTPUT_WIDTH 113
#define MPOOL_MAX_OUTPUT_HEIGHT 113
#define MPOOL_MAX_CONV_INPUT MPOOL_MAX_INPUT_DIMS*MPOOL_MAX_INPUT_WIDTH*MPOOL_MAX_INPUT_HEIGHT 
#define MPOOL_MAX_CONV_OUTPUT MPOOL_MAX_OUTPUT_DIMS*MPOOL_MAX_OUTPUT_WIDTH*MPOOL_MAX_OUTPUT_HEIGHT 
#define MPOOL_MAXPOOL_WINDOW 2

/* ----- FC LAYER -----*/

#define FC_MAX_INPUT_SIZE 25088 
#define FC_MAX_OUTPUT_SIZE 4096
#define FC_MAX_WEIGHT_SIZE FC_MAX_INPUT_SIZE*FC_MAX_OUTPUT_SIZE

